version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-frontend
    ports:
      - "3000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"